#include <stdio.h>

void PrintLicense() {
	printf("Copyright (c) 2013-2014 RapidPrime Developers\n");
	printf("\n");
	printf("Permission is hereby granted, free of charge, to any person obtaining a copy\n");
	printf("of this Primecoin software and associated documentation files (the \"oftware\",\n");
	printf("to deal in the Software without restriction, including without limitation the\n");
	printf("rights to use, copy, modify, merge, publish, distribute, sublicense, and/or\n");
	printf("sell copies of the Software, and to permit persons to whom the Software is\n");
	printf("furnished to do so, subject to the following conditions:\n");
	printf("\n");
	printf("1) Any world record in Cunningham chains and bi-twin chains achieved through\n");
	printf("the use of primecoin or a derivative work of primecoin shall credit primecoin\n");
	printf("as the first record holder of the record. Any world record in prime arithmetic\n");
	printf("progressions, prime constellations and other prime tuples achieved through the\n");
	printf("use of primecoin or a derivative work of primecoin shall credit primecoin among\n");
	printf("the record holders of the record.\n");
	printf("\n");
	printf("2) The above copyright notice and this permission notice shall be included in\n");
	printf("all copies or substantial portions of the Software.\n");
	printf("\n");
	printf("THE SOFTWARE IS PROVIDED \"S IS\" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n");
	printf("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n");
	printf("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n");
	printf("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n");
	printf("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n");
	printf("OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n");
	printf("THE SOFTWARE.\n");
	printf("\n");
	printf("Copyright (c) 2013 Primecoin Developers\n");
	printf("\n");
	printf("Permission is hereby granted, free of charge, to any person obtaining a copy\n");
	printf("of this Primecoin software and associated documentation files (the \"oftware\",\n");
	printf("to deal in the Software without restriction, including without limitation the\n");
	printf("rights to use, copy, modify, merge, publish, distribute, sublicense, and/or \n");
	printf("sell copies of the Software, and to permit persons to whom the Software is\n");
	printf("furnished to do so, subject to the following conditions:\n");
	printf("\n");
	printf("1) Any world record in Cunningham chains and bi-twin chains achieved through\n");
	printf("the use of primecoin or a derivative work of primecoin shall credit primecoin\n");
	printf("as the first record holder of the record. Any world record in prime arithmetic\n");
	printf("progressions, prime constellations and other prime tuples achieved through the\n");
	printf("use of primecoin or a derivative work of primecoin shall credit primecoin among\n");
	printf("the record holders of the record.\n");
	printf("\n");
	printf("2) The above copyright notice and this permission notice shall be included in\n");
	printf("all copies or substantial portions of the Software.\n");
	printf("\n");
	printf("THE SOFTWARE IS PROVIDED \"S IS\" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n");
	printf("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n");
	printf("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n");
	printf("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n");
	printf("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n");
	printf("OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n");
	printf("THE SOFTWARE.\n");
	printf("\n");
	printf("\n");
	printf("Copyright (c) 2009-2013 Bitcoin Developers\n");
	printf("\n");
	printf("Permission is hereby granted, free of charge, to any person obtaining a copy\n");
	printf("of the Bitcoin software and associated documentation files (the \"itcoin \n");
	printf("Software\", to deal in the Bitcoin Software without restriction, including \n");
	printf("without limitation the rights to use, copy, modify, merge, publish, distribute,\n");
	printf("sublicense, and/or sell copies of the Bitcoin Software, and to permit persons\n");
	printf("to whom the Bitcoin Software is furnished to do so, subject to the following\n");
	printf("conditions:\n");
	printf("\n");
	printf("The above copyright notice and this permission notice shall be included in\n");
	printf("all copies or substantial portions of the Bitcoin Software.\n");
	printf("\n");
	printf("THE SOFTWARE IS PROVIDED \"S IS\" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n");
	printf("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n");
	printf("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n");
	printf("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n");
	printf("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n");
	printf("OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n");
	printf("THE SOFTWARE.\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("Copyright (c) 2011-2013 PPCoin Developers\n");
	printf("\n");
	printf("Permission is hereby granted, free of charge, to any person obtaining a copy\n");
	printf("of the PPCoin software and associated documentation files (the \"PCoin \n");
	printf("Software\", to deal in the PPCoin Software without restriction, including\n");
	printf("without limitation the rights to use, copy, modify, merge, publish, distribute,\n");
	printf("sublicense, and/or sell copies of the PPCoin Software, and to permit persons\n");
	printf("to whom the PPCoin Software is furnished to do so, subject to the following\n");
	printf("conditions:\n");
	printf("\n");
	printf("The above copyright notice and this permission notice shall be included in\n");
	printf("all copies or substantial portions of the PPCoin Software.\n");
	printf("\n");
	printf("THE SOFTWARE IS PROVIDED \"S IS\" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n");
	printf("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n");
	printf("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n");
	printf("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n");
	printf("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n");
	printf("OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n");
	printf("THE SOFTWARE.\n");
	printf("\n");
	printf("\n");
	printf("/* ====================================================================\n");
	printf(" * Copyright (c) 1998-2011 The OpenSSL Project.  All rights reserved.\n");
	printf(" *\n");
	printf(" * Redistribution and use in source and binary forms, with or without\n");
	printf(" * modification, are permitted provided that the following conditions\n");
	printf(" * are met:\n");
	printf(" *\n");
	printf(" * 1. Redistributions of source code must retain the above copyright\n");
	printf(" *    notice, this list of conditions and the following disclaimer.\n");
	printf(" *\n");
	printf(" * 2. Redistributions in binary form must reproduce the above copyright\n");
	printf(" *    notice, this list of conditions and the following disclaimer in\n");
	printf(" *    the documentation and/or other materials provided with the\n");
	printf(" *    distribution.\n");
	printf(" *\n");
	printf(" * 3. All advertising materials mentioning features or use of this\n");
	printf(" *    software must display the following acknowledgment:\n");
	printf(" *    \"his product includes software developed by the OpenSSL Project\n");
	printf(" *    for use in the OpenSSL Toolkit. (http://www.openssl.org/)\"\n");
	printf(" *\n");
	printf(" * 4. The names \"penSSL Toolkit\"and \"penSSL Project\"must not be used to\n");
	printf(" *    endorse or promote products derived from this software without\n");
	printf(" *    prior written permission. For written permission, please contact\n");
	printf(" *    openssl-core@openssl.org.\n");
	printf(" *\n");
	printf(" * 5. Products derived from this software may not be called \"penSSL\"\n");
	printf(" *    nor may \"penSSL\"appear in their names without prior written\n");
	printf(" *    permission of the OpenSSL Project.\n");
	printf(" *\n");
	printf(" * 6. Redistributions of any form whatsoever must retain the following\n");
	printf(" *    acknowledgment:\n");
	printf(" *    \"his product includes software developed by the OpenSSL Project\n");
	printf(" *    for use in the OpenSSL Toolkit (http://www.openssl.org/)\"\n");
	printf(" *\n");
	printf(" * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY\n");
	printf(" * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n");
	printf(" * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n");
	printf(" * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR\n");
	printf(" * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n");
	printf(" * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT\n");
	printf(" * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n");
	printf(" * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n");
	printf(" * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\n");
	printf(" * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n");
	printf(" * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\n");
	printf(" * OF THE POSSIBILITY OF SUCH DAMAGE.\n");
	printf(" * ====================================================================\n");
	printf(" *\n");
	printf(" * This product includes cryptographic software written by Eric Young\n");
	printf(" * (eay@cryptsoft.com).  This product includes software written by Tim\n");
	printf(" * Hudson (tjh@cryptsoft.com).\n");
	printf(" *\n");
	printf(" */\n");
	printf("\n");
	printf(" Original SSLeay License\n");
	printf(" -----------------------\n");
	printf("\n");
	printf("/* Copyright (C) 1995-1998 Eric Young (eay@cryptsoft.com)\n");
	printf(" * All rights reserved.\n");
	printf(" *\n");
	printf(" * This package is an SSL implementation written\n");
	printf(" * by Eric Young (eay@cryptsoft.com).\n");
	printf(" * The implementation was written so as to conform with Netscapes SSL.\n");
	printf(" *\n");
	printf(" * This library is free for commercial and non-commercial use as long as\n");
	printf(" * the following conditions are aheared to.  The following conditions\n");
	printf(" * apply to all code found in this distribution, be it the RC4, RSA,\n");
	printf(" * lhash, DES, etc., code; not just the SSL code.  The SSL documentation\n");
	printf(" * included with this distribution is covered by the same copyright terms\n");
	printf(" * except that the holder is Tim Hudson (tjh@cryptsoft.com).\n");
	printf(" *\n");
	printf(" * Copyright remains Eric Young's, and as such any Copyright notices in\n");
	printf(" * the code are not to be removed.\n");
	printf(" * If this package is used in a product, Eric Young should be given attribution\n");
	printf(" * as the author of the parts of the library used.\n");
	printf(" * This can be in the form of a textual message at program startup or\n");
	printf(" * in documentation (online or textual) provided with the package.\n");
	printf(" *\n");
	printf(" * Redistribution and use in source and binary forms, with or without\n");
	printf(" * modification, are permitted provided that the following conditions\n");
	printf(" * are met:\n");
	printf(" * 1. Redistributions of source code must retain the copyright\n");
	printf(" *    notice, this list of conditions and the following disclaimer.\n");
	printf(" * 2. Redistributions in binary form must reproduce the above copyright\n");
	printf(" *    notice, this list of conditions and the following disclaimer in the\n");
	printf(" *    documentation and/or other materials provided with the distribution.\n");
	printf(" * 3. All advertising materials mentioning features or use of this software\n");
	printf(" *    must display the following acknowledgement:\n");
	printf(" *    \"his product includes cryptographic software written by\n");
	printf(" *     Eric Young (eay@cryptsoft.com)\"\n");
	printf(" *    The word 'cryptographic' can be left out if the rouines from the library\n");
	printf(" *    being used are not cryptographic related :-).\n");
	printf(" * 4. If you include any Windows specific code (or a derivative thereof) from\n");
	printf(" *    the apps directory (application code) you must include an acknowledgement:\n");
	printf(" *    \"his product includes software written by Tim Hudson (tjh@cryptsoft.com)\"\n");
	printf(" *\n");
	printf(" * THIS SOFTWARE IS PROVIDED BY ERIC YOUNG ``AS IS'' AND\n");
	printf(" * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n");
	printf(" * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n");
	printf(" * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE\n");
	printf(" * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n");
	printf(" * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS\n");
	printf(" * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n");
	printf(" * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n");
	printf(" * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY\n");
	printf(" * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\n");
	printf(" * SUCH DAMAGE.\n");
	printf(" *\n");
	printf(" * The licence and distribution terms for any publically available version or\n");
	printf(" * derivative of this code cannot be changed.  i.e. this code cannot simply be\n");
	printf(" * copied and put under another distribution licence\n");
	printf(" * [including the GNU Public Licence.]\n");
	printf(" */\n");
	printf("\n");
	printf("This software uses GMP under the terms of the LGPL:\n");
	printf("\n");
	printf("                   GNU LESSER GENERAL PUBLIC LICENSE\n");
	printf("                       Version 3, 29 June 2007\n");
	printf("\n");
	printf(" Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>\n");
	printf(" Everyone is permitted to copy and distribute verbatim copies\n");
	printf(" of this license document, but changing it is not allowed.\n");
	printf("\n");
	printf("\n");
	printf("  This version of the GNU Lesser General Public License incorporates\n");
	printf("the terms and conditions of version 3 of the GNU General Public\n");
	printf("License, supplemented by the additional permissions listed below.\n");
	printf("\n");
	printf("  0. Additional Definitions.\n");
	printf("\n");
	printf("  As used herein, \"his License\"refers to version 3 of the GNU Lesser\n");
	printf("General Public License, and the \"NU GPL\"refers to version 3 of the GNU\n");
	printf("General Public License.\n");
	printf("\n");
	printf("  \"he Library\"refers to a covered work governed by this License,\n");
	printf("other than an Application or a Combined Work as defined below.\n");
	printf("\n");
	printf("  An \"pplication\"is any work that makes use of an interface provided\n");
	printf("by the Library, but which is not otherwise based on the Library.\n");
	printf("Defining a subclass of a class defined by the Library is deemed a mode\n");
	printf("of using an interface provided by the Library.\n");
	printf("\n");
	printf("  A \"ombined Work\"is a work produced by combining or linking an\n");
	printf("Application with the Library.  The particular version of the Library\n");
	printf("with which the Combined Work was made is also called the \"inked\n");
	printf("Version\"\n");
	printf("\n");
	printf("  The \"inimal Corresponding Source\"for a Combined Work means the\n");
	printf("Corresponding Source for the Combined Work, excluding any source code\n");
	printf("for portions of the Combined Work that, considered in isolation, are\n");
	printf("based on the Application, and not on the Linked Version.\n");
	printf("\n");
	printf("  The \"orresponding Application Code\"for a Combined Work means the\n");
	printf("object code and/or source code for the Application, including any data\n");
	printf("and utility programs needed for reproducing the Combined Work from the\n");
	printf("Application, but excluding the System Libraries of the Combined Work.\n");
	printf("\n");
	printf("  1. Exception to Section 3 of the GNU GPL.\n");
	printf("\n");
	printf("  You may convey a covered work under sections 3 and 4 of this License\n");
	printf("without being bound by section 3 of the GNU GPL.\n");
	printf("\n");
	printf("  2. Conveying Modified Versions.\n");
	printf("\n");
	printf("  If you modify a copy of the Library, and, in your modifications, a\n");
	printf("facility refers to a function or data to be supplied by an Application\n");
	printf("that uses the facility (other than as an argument passed when the\n");
	printf("facility is invoked), then you may convey a copy of the modified\n");
	printf("version:\n");
	printf("\n");
	printf("   a) under this License, provided that you make a good faith effort to\n");
	printf("   ensure that, in the event an Application does not supply the\n");
	printf("   function or data, the facility still operates, and performs\n");
	printf("   whatever part of its purpose remains meaningful, or\n");
	printf("\n");
	printf("   b) under the GNU GPL, with none of the additional permissions of\n");
	printf("   this License applicable to that copy.\n");
	printf("\n");
	printf("  3. Object Code Incorporating Material from Library Header Files.\n");
	printf("\n");
	printf("  The object code form of an Application may incorporate material from\n");
	printf("a header file that is part of the Library.  You may convey such object\n");
	printf("code under terms of your choice, provided that, if the incorporated\n");
	printf("material is not limited to numerical parameters, data structure\n");
	printf("layouts and accessors, or small macros, inline functions and templates\n");
	printf("(ten or fewer lines in length), you do both of the following:\n");
	printf("\n");
	printf("   a) Give prominent notice with each copy of the object code that the\n");
	printf("   Library is used in it and that the Library and its use are\n");
	printf("   covered by this License.\n");
	printf("\n");
	printf("   b) Accompany the object code with a copy of the GNU GPL and this license\n");
	printf("   document.\n");
	printf("\n");
	printf("  4. Combined Works.\n");
	printf("\n");
	printf("  You may convey a Combined Work under terms of your choice that,\n");
	printf("taken together, effectively do not restrict modification of the\n");
	printf("portions of the Library contained in the Combined Work and reverse\n");
	printf("engineering for debugging such modifications, if you also do each of\n");
	printf("the following:\n");
	printf("\n");
	printf("   a) Give prominent notice with each copy of the Combined Work that\n");
	printf("   the Library is used in it and that the Library and its use are\n");
	printf("   covered by this License.\n");
	printf("\n");
	printf("   b) Accompany the Combined Work with a copy of the GNU GPL and this license\n");
	printf("   document.\n");
	printf("\n");
	printf("   c) For a Combined Work that displays copyright notices during\n");
	printf("   execution, include the copyright notice for the Library among\n");
	printf("   these notices, as well as a reference directing the user to the\n");
	printf("   copies of the GNU GPL and this license document.\n");
	printf("\n");
	printf("   d) Do one of the following:\n");
	printf("\n");
	printf("       0) Convey the Minimal Corresponding Source under the terms of this\n");
	printf("       License, and the Corresponding Application Code in a form\n");
	printf("       suitable for, and under terms that permit, the user to\n");
	printf("       recombine or relink the Application with a modified version of\n");
	printf("       the Linked Version to produce a modified Combined Work, in the\n");
	printf("       manner specified by section 6 of the GNU GPL for conveying\n");
	printf("       Corresponding Source.\n");
	printf("\n");
	printf("       1) Use a suitable shared library mechanism for linking with the\n");
	printf("       Library.  A suitable mechanism is one that (a) uses at run time\n");
	printf("       a copy of the Library already present on the user's computer\n");
	printf("       system, and (b) will operate properly with a modified version\n");
	printf("       of the Library that is interface-compatible with the Linked\n");
	printf("       Version.\n");
	printf("\n");
	printf("   e) Provide Installation Information, but only if you would otherwise\n");
	printf("   be required to provide such information under section 6 of the\n");
	printf("   GNU GPL, and only to the extent that such information is\n");
	printf("   necessary to install and execute a modified version of the\n");
	printf("   Combined Work produced by recombining or relinking the\n");
	printf("   Application with a modified version of the Linked Version. (If\n");
	printf("   you use option 4d0, the Installation Information must accompany\n");
	printf("   the Minimal Corresponding Source and Corresponding Application\n");
	printf("   Code. If you use option 4d1, you must provide the Installation\n");
	printf("   Information in the manner specified by section 6 of the GNU GPL\n");
	printf("   for conveying Corresponding Source.)\n");
	printf("\n");
	printf("  5. Combined Libraries.\n");
	printf("\n");
	printf("  You may place library facilities that are a work based on the\n");
	printf("Library side by side in a single library together with other library\n");
	printf("facilities that are not Applications and are not covered by this\n");
	printf("License, and convey such a combined library under terms of your\n");
	printf("choice, if you do both of the following:\n");
	printf("\n");
	printf("   a) Accompany the combined library with a copy of the same work based\n");
	printf("   on the Library, uncombined with any other library facilities,\n");
	printf("   conveyed under the terms of this License.\n");
	printf("\n");
	printf("   b) Give prominent notice with the combined library that part of it\n");
	printf("   is a work based on the Library, and explaining where to find the\n");
	printf("   accompanying uncombined form of the same work.\n");
	printf("\n");
	printf("  6. Revised Versions of the GNU Lesser General Public License.\n");
	printf("\n");
	printf("  The Free Software Foundation may publish revised and/or new versions\n");
	printf("of the GNU Lesser General Public License from time to time. Such new\n");
	printf("versions will be similar in spirit to the present version, but may\n");
	printf("differ in detail to address new problems or concerns.\n");
	printf("\n");
	printf("  Each version is given a distinguishing version number. If the\n");
	printf("Library as you received it specifies that a certain numbered version\n");
	printf("of the GNU Lesser General Public License \"r any later version\"\n");
	printf("applies to it, you have the option of following the terms and\n");
	printf("conditions either of that published version or of any later version\n");
	printf("published by the Free Software Foundation. If the Library as you\n");
	printf("received it does not specify a version number of the GNU Lesser\n");
	printf("General Public License, you may choose any version of the GNU Lesser\n");
	printf("General Public License ever published by the Free Software Foundation.\n");
	printf("\n");
	printf("  If the Library as you received it specifies that a proxy can decide\n");
	printf("whether future versions of the GNU Lesser General Public License shall\n");
	printf("apply, that proxy's public statement of acceptance of any version is\n");
	printf("permanent authorization for you to choose that version for the\n");
	printf("Library.\n");
	printf("\n");
}
